
#- hosts: webservers
#  become: yes
#  roles:
  #  - exporter
#  - filebeat
#  - webservers
#- hosts: prometheus
#  become: yes
#  roles:
#  - prometheus
#  vars:
#    prometheus_targets:
#      node:
#      - targets:
#        - "192.168.2.18:9090"
#        - "192.168.1.19:9090"

#- hosts: kibana
#  become: yes
#  roles:
#  - docker
#  - kibana

#- hosts: grafana
#  become: yes
#  gather_facts: false

#  roles:
#  - docker
#  - grafana

- hosts: elastic
  become: yes
  roles:
#  - docker
  - elasticsearch
