
- hosts: webservers
  become: yes
  roles:
  - exporter
  - filebeat
  - webservers
- hosts: prometheus
  become: yes
  roles:
  - prometheus
  vars:
    prometheus_targets:
      node:
      - targets:
        - "epdkf34aosa2o2qucbqc.auto.internal:9090"
        - "fhmcoe4852df9ji8i818.auto.internal:9090"

- hosts: kibana
  become: yes
  roles:
  - docker
  - kibana

- hosts: grafana
  become: yes
  gather_facts: false

  roles:
  - docker
  - grafana

- hosts: elastic
  become: yes
  roles:
  - docker
  - elasticsearch
