galaxy_info:
  author: Gregory Stasenko
  description: role for webservers, installing Nginx and logexporter
  company: none

  license: license (GPL-2.0-or-later, MIT, etc)

  min_ansible_version: 2.1
  galaxy_tags: []
dependencies: []
