# tasks file for webservers

- name: Install Nginx
  yum:
    name: nginx
    state: present

- name: Write Nginx Index.html
  template:
    src: index.html.j2
    dest: /usr/share/nginx/html/index.html

- name: Write Nginx config
  template:
    src: default.conf.j2
    dest: /etc/nginx/nginx.conf

- name: Restart Nginx
  service:
    name: nginx
    state: restarted

- name: Ensure Nginx is enabled on boot
  systemd:
    daemon_reload: true
    name: nginx
    enabled: true

- import_tasks: preflight.yml

- import_tasks: install.yml

- name: Ensure Nginxlog Exporter is enabled on boot
  systemd:
    daemon_reload: true
    name: nginxlog_exporter
    enabled: true

