- name: Create elastic search volume
  docker_volume:
    name: esdata
    driver: local

- name: Create folder
  file:
    path: /opt/elastic/config/
    state: directory

- name: Copy elasticsearch.yml
  ansible.builtin.copy:
    src: /home/greg/roles/elasticsearch/templates/elasticsearch.yml.j2
    dest: /opt/elastic/config/elasticsearch.yml

- name: Start elastic search container
  community.docker.docker_container:
    name: elasticsearch
    image: elasticsearch:8.14.3
    env:
      discovery.type: "single-node"
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
      xpack.security.enabled: "true"
      xpack.monitoring.collection.enabled: "true"
    volumes:
    - "esdata:/usr/share/elasticsearch/data"
    - /opt/elastic/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    exposed_ports:
    - 9200/tcp
    - 9300/tcp
    ports:
    - 9200:9200
    - 9300:9300
    ulimits:
    - nofile:65535:65535
    state: started
    log_driver: syslog
    log_opt:
      syslog-facility: local0
      tag: elastic
    pull: false
    restart_policy: always
    state: started

- debug:
    msg: >
      Users have to be configured manually. Enable and set the password for the default users with: `docker exec -it elasticsearch /bin/bash -c "elasticsearch-setup-passwords auto"` Then edit the `vaul.yml` file and copy the password values to the expected variable.
